# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressrelease',
            old_name='release_url',
            new_name='url',
        ),
    ]
