# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_pressrelease_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='p_tag_text',
            field=models.TextField(default=b''),
        ),
    ]
