# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20161011_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='polarity_score',
            field=models.TextField(default=b''),
        ),
    ]
