# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_pressrelease_polarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='p_tag_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='polarity_score',
            field=models.TextField(default=''),
        ),
    ]
